### ISSUE TITLE
Has anyone got this error? Authentication Failed

### ISSUE THREAD

**Issue by xil45** [s-rah/onionscan#132]
[!!!] Killed the onionscan process.
Exception in thread Thread-71:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "./onionrunner.py", line 98, in handle_timeout
    torcontrol.authenticate("PythonRocks")
  File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 1071, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stem/connection.py", line 618, in authenticate
    raise auth_exc
IncorrectPassword: Authentication failed: Password did not match HashedControlPassword *or* authentication cookie.

**Comment by s-rah** [comment]
This is a python stacktrace, onionscan is written in go - we cannot provide support for wrappers for onionscan.

That being said, looks like the Tor config you are running with is expecting a password that is not matching the one the python wrapper is providing.
